# Generated by Django 4.1.9 on 2023-10-04 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('life', models.TextField()),
                ('image', models.ImageField(upload_to='author_images')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('books_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('image', models.ImageField(upload_to='media/books')),
                ('category', models.CharField(choices=[('RM', 'ROMANTIKA'), ('CM', 'COMEDIYA'), ('MD', 'MAKTAB DARSLIKLARI'), ('SH', 'SHERIYAT')], max_length=4)),
                ('pdf', models.FileField(upload_to='pdf_books')),
                ('views_count', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paginationapp.author')),
            ],
        ),
    ]
