# Generated by Django 4.1.9 on 2023-07-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginationapp', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='category',
            field=models.CharField(choices=[('RM', 'ROMANTIKA'), ('CM', 'COMEDIYA'), ('MD', 'MAKTAB DARSLIKLARI'), ('SH', 'SHERIYAT')], default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='lastname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
