# Generated by Django 4.1.9 on 2023-07-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginationapp', '0004_author_category_alter_author_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('RM', 'ROMANTIKA'), ('CM', 'COMEDIYA'), ('MD', 'MAKTAB DARSLIKLARI'), ('SH', 'SHERIYAT')], default='', max_length=4),
            preserve_default=False,
        ),
    ]
