# Generated by Django 4.1.9 on 2023-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginationapp', '0006_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to='pdf_books'),
        ),
    ]
