# Generated by Django 4.1.9 on 2023-07-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginationapp', '0008_author_books_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
