# Generated by Django 4.1.9 on 2023-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginationapp', '0009_book_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
