# Generated by Django 4.1.9 on 2023-10-05 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_firstname_customuser_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/profile_pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
