# Generated by Django 4.2.6 on 2023-12-09 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('life', models.TextField()),
                ('image', models.ImageField(blank=True, default='author_images/images.png', null=True, upload_to='author_images')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('books_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='media/books/bookwithoutcover.jpg', null=True, upload_to='media/books')),
                ('category', models.CharField(choices=[('RM', 'BADIIY'), ('CM', 'DINIY'), ('MD', 'MAKTAB DARSLIKLARI'), ('SH', 'BOLALAR')], max_length=4)),
                ('pdf', models.FileField(upload_to='pdf_books')),
                ('views_count', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookhiveapp.author')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
