# Generated by Django 4.2.6 on 2023-12-08 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookhiveapp', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='book',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='bookhiveapp.book'),
            preserve_default=False,
        ),
    ]
